{
 "title": "Packagist repository stat",
 "templating": {
  "list": [
   { "name": "repository", "query": { "query": "packagist_downloads" } }
  ]
 },
 "panels": [
  { "title": "Stars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dailty Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "packagist_downloads_daily{package=\"$repository\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Monthly downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "packagist_downloads_monthly{package=\"$repository\"}",
     "legendFormat": "{{package}}"
    }
   ]
  },
  {
   "title": "Total downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "packagist_downloads{package=\"$repository\"}",
     "legendFormat": "{{package}}"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "predict_linear(packagist_downloads_daily{package=\"$repository\"}[24h], 60)",
     "legendFormat": "Daily"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "packagist_downloads_daily{package=\"$repository\"}",
     "legendFormat": "Daily"
    },
    {
     "expr": "packagist_downloads_monthly{package=\"$repository\"}",
     "legendFormat": "Monthly"
    },
    {
     "expr": "packagist_downloads{package=\"$repository\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}