{
 "title": "Packagist",
 "panels": [
  {
   "title": "Daily Installs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(packagist_downloads_daily[24h])",
     "legendFormat": "{{package}}"
    }
   ]
  },
  {
   "title": "Monthly Installs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "packagist_downloads_monthly", "legendFormat": "{{package}}" }
   ]
  },
  {
   "title": "Total Installs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "packagist_downloads", "legendFormat": "{{package}}" }
   ]
  }
 ]
}